import { jsPDF } from 'jspdf';
import { subjects } from '@/data/subjects';
import { toast } from 'sonner';

interface ProgressData {
  [subjectId: string]: { [topicId: string]: boolean };
}

export const exportProgressPDF = (
  username: string,
  studyId: string,
  progress: ProgressData
) => {
  try {
    const doc = new jsPDF();
    const pageWidth = doc.internal.pageSize.getWidth();
    let y = 20;

    // Header
    doc.setFontSize(22);
    doc.setFont('helvetica', 'bold');
    doc.text('ExamPrep Pro', pageWidth / 2, y, { align: 'center' });
    y += 8;
    doc.setFontSize(12);
    doc.setFont('helvetica', 'normal');
    doc.text('Progress Report Card', pageWidth / 2, y, { align: 'center' });
    y += 12;

    // Line separator
    doc.setDrawColor(234, 179, 8);
    doc.setLineWidth(1);
    doc.line(20, y, pageWidth - 20, y);
    y += 10;

    // User info
    doc.setFontSize(11);
    doc.setFont('helvetica', 'bold');
    doc.text(`Student: ${username}`, 20, y);
    doc.text(`Study ID: ${studyId}`, pageWidth - 20, y, { align: 'right' });
    y += 6;
    doc.setFont('helvetica', 'normal');
    doc.text(`Generated: ${new Date().toLocaleDateString('en-IN', { day: 'numeric', month: 'long', year: 'numeric' })}`, 20, y);
    y += 12;

    // Overall stats
    let totalCompleted = 0;
    let totalTopics = 0;

    subjects.forEach(subject => {
      const subjectTopics = subject.units.reduce((acc, unit) =>
        acc + unit.topics.filter(t => !t.isHeading).length, 0);
      const completed = progress[subject.id]
        ? Object.values(progress[subject.id]).filter(Boolean).length
        : 0;
      totalCompleted += completed;
      totalTopics += subjectTopics;
    });

    const overallPercent = totalTopics > 0 ? Math.round((totalCompleted / totalTopics) * 100) : 0;

    doc.setFontSize(14);
    doc.setFont('helvetica', 'bold');
    doc.text('Overall Progress', 20, y);
    y += 8;

    // Progress bar
    doc.setFillColor(30, 30, 50);
    doc.roundedRect(20, y, pageWidth - 40, 8, 2, 2, 'F');
    doc.setFillColor(234, 179, 8);
    doc.roundedRect(20, y, (pageWidth - 40) * (overallPercent / 100), 8, 2, 2, 'F');
    doc.setFontSize(9);
    doc.setTextColor(255, 255, 255);
    doc.text(`${overallPercent}% (${totalCompleted}/${totalTopics} topics)`, pageWidth / 2, y + 6, { align: 'center' });
    doc.setTextColor(0, 0, 0);
    y += 16;

    // Per-subject breakdown
    doc.setFontSize(14);
    doc.setFont('helvetica', 'bold');
    doc.text('Subject Breakdown', 20, y);
    y += 10;

    subjects.forEach((subject) => {
      if (y > 260) {
        doc.addPage();
        y = 20;
      }

      const subjectTopics = subject.units.reduce((acc, unit) =>
        acc + unit.topics.filter(t => !t.isHeading).length, 0);
      const completed = progress[subject.id]
        ? Object.values(progress[subject.id]).filter(Boolean).length
        : 0;
      const percent = subjectTopics > 0 ? Math.round((completed / subjectTopics) * 100) : 0;

      doc.setFontSize(10);
      doc.setFont('helvetica', 'bold');
      doc.text(subject.name, 20, y);
      doc.setFont('helvetica', 'normal');
      doc.text(`${completed}/${subjectTopics} (${percent}%)`, pageWidth - 20, y, { align: 'right' });
      y += 5;

      // Mini progress bar
      doc.setFillColor(40, 40, 60);
      doc.roundedRect(20, y, pageWidth - 40, 5, 1, 1, 'F');
      const barColor = percent >= 75 ? [34, 197, 94] : percent >= 40 ? [234, 179, 8] : [239, 68, 68];
      doc.setFillColor(barColor[0], barColor[1], barColor[2]);
      if (percent > 0) {
        doc.roundedRect(20, y, (pageWidth - 40) * (percent / 100), 5, 1, 1, 'F');
      }
      y += 12;
    });

    // Footer
    y += 5;
    doc.setDrawColor(200, 200, 200);
    doc.setLineWidth(0.5);
    doc.line(20, y, pageWidth - 20, y);
    y += 8;
    doc.setFontSize(8);
    doc.setTextColor(128, 128, 128);
    doc.text('Generated by ExamPrep Pro | examprep.vercel.app', pageWidth / 2, y, { align: 'center' });

    doc.save(`ExamPrep_Report_${username}_${new Date().toISOString().split('T')[0]}.pdf`);
    toast.success('Report downloaded!');
  } catch (error) {
    console.error('PDF export error:', error);
    toast.error('Failed to generate PDF');
  }
};
